# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wineapp', '0002_cluster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='users',
        ),
        migrations.DeleteModel(
            name='Cluster',
        ),
    ]
