# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineapp', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
