# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineapp', '0005_wine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
