# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineapp', '0006_auto_20160127_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='abv',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wine',
            name='variety',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
