# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineapp', '0007_auto_20160128_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='abv',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
