# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineapp', '0009_wine_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='abv',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='variety',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
