# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20151204_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='name',
            field=models.TextField(default='test_box'),
            preserve_default=False,
        ),
    ]
