# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_box_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
