# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_box_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='logo_url',
            field=models.CharField(max_length=50),
        ),
    ]
