# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='source',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
