# Generated by Django 2.2rc1 on 2019-04-01 01:32

from django.db import migrations, models
from django.db.models import F, Value as V
from django.db.models.functions import Left, StrIndex, Substr


def extract_authors(apps, schema_editor):
    """
    Remove authors from subtitles, copy to author field, and remove from subtitle text.

    Example: "blah -- some guy"
        hyphens_location = 5 (1-indexed)
        text = "some guy"
        author = "blah"
    """
    Subtitle = apps.get_model("home", "Subtitle")
    subtitles = Subtitle.objects.annotate(hyphens_location=StrIndex('text', V(' -- ')))
    subtitles_with_authors = subtitles.filter(hyphens_location__gt=0)
    subtitles_with_authors.update(
        author=Substr('text', F('hyphens_location') + 4),
        text=Left('text', F('hyphens_location') - 1)
    )


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170119_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='author',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.RunPython(extract_authors)
    ]
